---
abstract: 'ClassName type constraint with coercion to load the class.'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Moose: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-LoadableClass
no_index:
  directory:
    - inc
    - t
requires:
  Class::Load: 0.06
  MooseX::Types: 0.22
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/karenetheridge/MooseX-Types-LoadableClass.git
version: 0.009
